name: Sync EMU -> Public (main only, no workflows)

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Generate installation token (EMU source)
        id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: cato-networks-CTRL
          repositories: ${{ github.event.repository.name }}

      - name: Ensure public repo exists
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
          PUBLIC_ORG: Cato-CTRL
        run: |
          set -euo pipefail

          # Check if repo already exists
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${PUBLIC_REPO_TOKEN}" \
            "https://api.github.com/repos/${PUBLIC_ORG}/${REPO_NAME}")

          if [ "$STATUS" = "200" ]; then
            echo "Public repo ${PUBLIC_ORG}/${REPO_NAME} already exists, skipping creation."
          else
            echo "Creating public repo ${PUBLIC_ORG}/${REPO_NAME}..."
            curl -sf -X POST \
              -H "Authorization: token ${PUBLIC_REPO_TOKEN}" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/orgs/${PUBLIC_ORG}/repos" \
              -d "{
                \"name\": \"${REPO_NAME}\",
                \"visibility\": \"public\",
                \"description\": \"Public mirror of ${REPO_NAME}\",
                \"has_issues\": false,
                \"has_projects\": false,
                \"has_wiki\": false
              }"
            echo "Created successfully."
          fi

      - name: Clone source (main)
        run: |
          set -euo pipefail
          SRC_URL="https://x-access-token:${{ steps.app_token.outputs.token }}@github.com/${{ github.repository }}.git"
          git clone --no-tags --single-branch --branch main "$SRC_URL" repo
          cd repo
          git rev-parse --short HEAD

      - name: Remove workflows from history (rewrite)
        run: |
          set -euo pipefail
          cd repo
          git filter-branch -f --prune-empty --index-filter \
            "git rm -r --cached --ignore-unmatch .github/workflows" \
            -- --all
          rm -rf .git/refs/original
          git reflog expire --expire=now --all
          git gc --prune=now --aggressive

      - name: Push main to public
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
          REPO_NAME: ${{ github.event.repository.name }}
          PUBLIC_ORG: Cato-CTRL
        run: |
          set -euo pipefail
          cd repo
          DEST_URL="https://x-access-token:${PUBLIC_REPO_TOKEN}@github.com/${PUBLIC_ORG}/${REPO_NAME}.git"
          git remote remove origin || true
          git remote add public "$DEST_URL"
          git push public HEAD:main --force
          echo "Sync to ${PUBLIC_ORG}/${REPO_NAME} completed"
